<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Principal Component Regression (PCR)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="pcr_files/libs/clipboard/clipboard.min.js"></script>
<script src="pcr_files/libs/quarto-html/quarto.js"></script>
<script src="pcr_files/libs/quarto-html/popper.min.js"></script>
<script src="pcr_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="pcr_files/libs/quarto-html/anchor.min.js"></script>
<link href="pcr_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="pcr_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="pcr_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="pcr_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="pcr_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#motivation-for-pcr" id="toc-motivation-for-pcr" class="nav-link active" data-scroll-target="#motivation-for-pcr">Motivation for PCR</a></li>
  <li><a href="#modeling-pcr" id="toc-modeling-pcr" class="nav-link" data-scroll-target="#modeling-pcr">Modeling PCR</a></li>
  <li><a href="#principal-component-matrix-z-for-our-data." id="toc-principal-component-matrix-z-for-our-data." class="nav-link" data-scroll-target="#principal-component-matrix-z-for-our-data.">Principal component Matrix <span class="math inline">\(Z\)</span>, for our data.</a></li>
  <li><a href="#principal-components-are-uncorrolated" id="toc-principal-components-are-uncorrolated" class="nav-link" data-scroll-target="#principal-components-are-uncorrolated">Principal components are uncorrolated:</a></li>
  <li><a href="#full-pcr-model" id="toc-full-pcr-model" class="nav-link" data-scroll-target="#full-pcr-model">Full PCR Model</a></li>
  <li><a href="#reduced-pcr-model" id="toc-reduced-pcr-model" class="nav-link" data-scroll-target="#reduced-pcr-model">Reduced PCR Model</a></li>
  <li><a href="#model-assumption-for-pcr" id="toc-model-assumption-for-pcr" class="nav-link" data-scroll-target="#model-assumption-for-pcr">Model Assumption for PCR</a></li>
  <li><a href="#final-pcr-model-in-terms-of-the-original-predictors" id="toc-final-pcr-model-in-terms-of-the-original-predictors" class="nav-link" data-scroll-target="#final-pcr-model-in-terms-of-the-original-predictors">Final PCR Model in Terms of the Original Predictors</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Principal Component Regression (PCR)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="motivation-for-pcr" class="level3">
<h3 class="anchored" data-anchor-id="motivation-for-pcr">Motivation for PCR</h3>
<p>In a linear regression model, when the predictors (<span class="math inline">\(X_i\)</span>s) are linearly dependent or highly correlated, we say that multicollinearity exists in the model, which causes the following issue for the fitted multiple regression model:</p>
<ul>
<li>The estimate of any parameter, say <span class="math inline">\(\hat{\beta_2}\)</span>, depends on all the variables included in the model. For example, <span class="math inline">\(\hat{\beta_2}\)</span> does not merely reflect the effect of the <span class="math inline">\(X_2\)</span> variable on the response variable <span class="math inline">\(Y\)</span>. Due to multicollinearity, the other variables affect the estimate of the parameter <span class="math inline">\(\beta_2\)</span>. As a result, our inference about the effect of each predictor on the response is not reliable.</li>
</ul>
<p>We have 15 predictors in our dataset, and we want to investigate the relationship between them and the response variable (mortality). There is a high correlation between most of the predictors. <a href="#fig-corr-xx" class="quarto-xref">Figure&nbsp;1</a> illustrates this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|warning: false</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#------------------Cleaning the memory</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#------------------Reading Data</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"bestglm"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(mcdonald)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------Centralize-Normalize Data</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>data.norm <span class="ot">&lt;-</span> data</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(data)){</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  data.norm[,i] <span class="ot">&lt;-</span> data[,i]<span class="sc">-</span><span class="fu">mean</span>(data[,i])</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  data.norm[,i] <span class="ot">&lt;-</span> data.norm[,i]<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">sum</span>((data.norm[,i])<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">#----------------Separating X and Y(Mort)</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>x.norm <span class="ot">&lt;-</span> data.norm</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>mort.norm <span class="ot">&lt;-</span> x.norm<span class="sc">$</span>MORT</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>x.norm<span class="sc">$</span>MORT <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">#----------------Correlation Plot for predictors (X)</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>res_xx <span class="ot">&lt;-</span> <span class="fu">cor</span>(x.norm, <span class="at">method=</span><span class="st">"pearson"</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.95 loaded</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(res_xx, <span class="at">method =</span> <span class="st">'ellipse'</span>, <span class="at">order =</span> <span class="st">'AOE'</span>, <span class="at">type =</span> <span class="st">'upper'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-corr-xx" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-corr-xx-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pcr_files/figure-html/fig-corr-xx-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-corr-xx-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Correlation plot for 15 predictors of the data set
</figcaption>
</figure>
</div>
</div>
</div>
<p>The correlation plot of the predictors indicates there is Multicolleniarity among predictors. For overcoming this issue the authors of the paper used Ridge Regression method and after exploring and comparing several Ridge and Ordinary Least Square models (Multiple Regression Models) they conclude that:</p>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>“In summary, the ridge regression coefficients obtained at <span class="math inline">\(k = o.2\)</span> for the fifteen explanatory variables listed in Table IV, with one notable exception(<span class="math inline">\(NO_x\)</span> ), appear to be reasonable values upon which to base a quantification of the association between these variables and the total mortality rate.”</p>
</div>
</div>
</div>
<p>In the following, we present a Principal Component Regression model with all fifteen predictors as an alternative model for overcoming multicollinearity and compare it with the final Ridge Regression model suggested by the authors.</p>
</section>
<section id="modeling-pcr" class="level3">
<h3 class="anchored" data-anchor-id="modeling-pcr">Modeling PCR</h3>
<p>In PCR, we try to provide a weighted linear combination of the predictors (<span class="math inline">\(X_i\)</span>s) like: <span class="math display">\[Z_k = v_{k1}X_1 + v_{k2}X_2 + \dots + v_{kp}X_p\]</span> We then replace the correlated variables <span class="math inline">\([X_1, X_2, \dots, X_p]\)</span> with <span class="math inline">\(Z = [Z_1, Z_2, \dots, Z_p]\)</span> which are uncorrelated, so the regression model <span class="math inline">\(y = Z\beta_z + \epsilon\)</span> does not suffer from multicollinearity.</p>
<p>First, we need to centralize and normalize all the variables for PCR. In the following, we assume the <span class="math inline">\(y\)</span> and <span class="math inline">\(X\)</span> variables are all centralized and normalized and show how to find the <span class="math inline">\(Z\)</span> matrix.</p>
<p><span class="math display">\[\text{Correlated: $X=[X_1, X_2, \dots, X_p]$ $\xrightarrow{\text{PC Analysis}}$ Uncorrelated: $Z=[Z_1, Z_2, \dots, Z_p]$}\]</span></p>
<p>We call <span class="math inline">\(Z_i\)</span> the i-th <strong>principal component</strong> of matrix <span class="math inline">\(X\)</span>.</p>
<p>In ordinary least squares,</p>
<p><span class="math display">\[\hat{\beta_x}=\left( X'X \right)^{-1}X'y\]</span></p>
<p>We perform PCA on matrix <span class="math inline">\(X\)</span> through singular value decomposition. We obtain <span class="math display">\[UDV'=X\]</span> <span class="math inline">\(U\)</span> is the left singular vectors matrix, <span class="math inline">\(D\)</span> is a diagonal matrix consisting of non-negative singular values, and <span class="math inline">\(V\)</span> is the matrix of the right singular vectors matrix (eigenvectors matrix). We calculate matrix <span class="math display">\[Z=XV\]</span></p>
<p>The columns of <span class="math inline">\(Z\)</span> are linearly independent. If we define</p>
<p><span class="math display">\[\hat{\beta_z}=\left( Z'Z \right)^{-1}Z'y\]</span> then:</p>
<p><span class="math display">\[\hat{y}=X\hat{\beta_x}=Z\hat{\beta_z}\]</span> So, We have the regression model <span class="math inline">\(y = Z\beta_z + \epsilon\)</span> without multilinearity, but gives the same predictions of the intial model <span class="math inline">\(y = X\beta_x + \epsilon\)</span>.</p>
</section>
<section id="principal-component-matrix-z-for-our-data." class="level3">
<h3 class="anchored" data-anchor-id="principal-component-matrix-z-for-our-data.">Principal component Matrix <span class="math inline">\(Z\)</span>, for our data.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>x.pca1 <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(x.norm)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> x.pca1<span class="sc">$</span>x</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             PC1        PC2         PC3         PC4         PC5          PC6
[1,] -0.04987469  0.1101067  0.02961315 -0.14558022  0.09674621  0.003565735
[2,] -0.13416693  0.1915341  0.01981072  0.14147444 -0.09377401 -0.046992635
[3,]  0.02910247  0.2741925 -0.14374289  0.10724793 -0.01966782 -0.127370437
[4,]  0.34147952 -0.2787947  0.14568029 -0.05010069 -0.01347359  0.049910630
[5,]  0.16777993 -0.1066177 -0.39445216 -0.18542657 -0.10291578  0.201877939
[6,]  0.62881414 -0.2951224 -0.12052807  0.06117279  0.11712605 -0.017487108
             PC7          PC8          PC9        PC10        PC11        PC12
[1,]  0.01139939  0.038200847  0.018426089  0.04065088  0.04081958 -0.03822061
[2,] -0.14759266 -0.095147609  0.010041287 -0.03229731  0.01024229  0.01832739
[3,]  0.13265654  0.049829663 -0.021000696 -0.01872396 -0.02161152  0.02266012
[4,] -0.03460280 -0.005695321  0.078419866 -0.06253758  0.01502470 -0.00140534
[5,]  0.05436756  0.086348757 -0.005532051 -0.06962401 -0.01803604  0.03112394
[6,] -0.15397859 -0.041560514  0.101957037  0.02193579  0.06792109 -0.01141108
             PC13        PC14         PC15
[1,] -0.053485777  0.01435260  0.001138392
[2,]  0.050625875  0.02907269 -0.006025665
[3,] -0.037043626  0.01451595 -0.003143513
[4,] -0.001265839  0.02782116  0.005515533
[5,]  0.024711923 -0.01427383  0.001537987
[6,] -0.008691758 -0.05564870 -0.004393290</code></pre>
</div>
</div>
</section>
<section id="principal-components-are-uncorrolated" class="level3">
<h3 class="anchored" data-anchor-id="principal-components-are-uncorrolated">Principal components are uncorrolated:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>res_zz <span class="ot">&lt;-</span> <span class="fu">cor</span>(z, <span class="at">method=</span><span class="st">"pearson"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(res_zz, <span class="at">method =</span> <span class="st">'ellipse'</span>, <span class="at">order =</span> <span class="st">'AOE'</span>, <span class="at">type =</span> <span class="st">'upper'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-cor-pc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cor-pc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pcr_files/figure-html/fig-cor-pc-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cor-pc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Correlation plot for 15 Principal Components (Columns of the matrix Z)
</figcaption>
</figure>
</div>
</div>
</div>
<p>One question is: after converting the matrix <span class="math inline">\(X\)</span> to <span class="math inline">\(Z\)</span>, how much of the information (variance) from the original matrix <span class="math inline">\(X\)</span> does the principal component matrix <span class="math inline">\(Z\)</span> retain?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>variation <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span><span class="fu">cbind</span>(x.pca1<span class="sc">$</span>sdev<span class="sc">/</span><span class="fu">sum</span>(x.pca1<span class="sc">$</span>sdev),<span class="fu">rep</span>(<span class="dv">0</span>    ,<span class="dv">15</span>),<span class="fu">cumsum</span>(x.pca1<span class="sc">$</span>sdev)<span class="sc">/</span><span class="fu">sum</span>(x.pca1<span class="sc">$</span>sdev))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(variation) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Var(%)"</span>,<span class="st">"   "</span>,<span class="st">"CumVar(%)"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(variation) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PC1"</span>,<span class="st">"PC2"</span>,<span class="st">"PC3"</span>,<span class="st">"PC4"</span>,<span class="st">"PC5"</span>,<span class="st">"PC6"</span>,<span class="st">"PC7"</span>,<span class="st">"PC8"</span>,<span class="st">"PC9"</span>,<span class="st">"PC10"</span>,<span class="st">"PC11"</span>,<span class="st">"PC12"</span>,<span class="st">"PC13"</span>,<span class="st">"PC14"</span>,<span class="st">"PC15"</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(variation[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)],<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Var(%) CumVar(%)
PC1    17.2      17.2
PC2    13.4      30.6
PC3    11.6      42.1
PC4     9.4      51.5
PC5     8.9      60.4
PC6     7.9      68.3
PC7     6.3      74.6
PC8     5.5      80.2
PC9     4.9      85.1
PC10    3.8      88.8
PC11    3.3      92.1
PC12    2.9      95.0
PC13    2.7      97.7
PC14    1.7      99.4
PC15    0.6     100.0</code></pre>
</div>
</div>
<p>The first principal component (<span class="math inline">\(PC_1\)</span>) only accounts <span class="math inline">\(27\)</span>% of the variation (information) of <span class="math inline">\(X\)</span> matrix, the first two principal components (<span class="math inline">\(PC_1\)</span> and <span class="math inline">\(PC_2\)</span>) account <span class="math inline">\(30\)</span>% of the <span class="math inline">\(X\)</span> matrix variation and so on. All the principal components matrix,<span class="math inline">\(Z=[PC_1, PC_2,\dots,PC_{15}]\)</span>, account <span class="math inline">\(100\)</span>% of the variation of of the <span class="math inline">\(X\)</span> matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ncol</span>(x.norm)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>PVE <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>,p)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>){ PVE[i]<span class="ot">&lt;-</span> variation[i,<span class="dv">3</span>] }</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>( PVE, <span class="at">names.arg =</span> <span class="dv">1</span><span class="sc">:</span>p, <span class="at">main =</span> <span class="st">"scree plot"</span>, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab =</span> <span class="st">"number of PCs"</span>, </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">ylab =</span> <span class="st">"% of variance explained"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-scree" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pcr_files/figure-html/fig-scree-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: The scree plot show the cumulative variance explained by principal components.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="full-pcr-model" class="level3">
<h3 class="anchored" data-anchor-id="full-pcr-model">Full PCR Model</h3>
<p>In the following we have fitted the Principal Component Regression model (<span class="math inline">\(\hat{y} = Z\hat{\beta_z}\)</span>) for our data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>data_pcr <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(z,mort.norm))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>full_pcr <span class="ot">&lt;-</span> <span class="fu">lm</span>(mort.norm <span class="sc">~</span>.,<span class="at">data=</span>data_pcr)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full_pcr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mort.norm ~ ., data = data_pcr)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.142453 -0.037707  0.001908  0.040232  0.181997 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.257e-17  9.437e-03   0.000  1.00000    
PC1          2.506e-01  3.435e-02   7.295 4.24e-09 ***
PC2         -5.291e-02  4.404e-02  -1.201  0.23603    
PC3         -3.187e-01  5.100e-02  -6.250 1.45e-07 ***
PC4         -4.341e-02  6.295e-02  -0.690  0.49404    
PC5         -1.155e-02  6.609e-02  -0.175  0.86212    
PC6          3.389e-01  7.459e-02   4.544 4.28e-05 ***
PC7         -2.787e-01  9.339e-02  -2.985  0.00462 ** 
PC8          1.129e-01  1.064e-01   1.061  0.29459    
PC9          3.000e-01  1.200e-01   2.499  0.01624 *  
PC10         2.150e-01  1.571e-01   1.368  0.17811    
PC11         2.351e-01  1.792e-01   1.312  0.19644    
PC12         4.698e-01  2.051e-01   2.290  0.02686 *  
PC13        -2.481e-01  2.165e-01  -1.146  0.25797    
PC14         7.431e-02  3.407e-01   0.218  0.82835    
PC15        -1.401e+00  1.048e+00  -1.336  0.18826    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0731 on 44 degrees of freedom
Multiple R-squared:  0.7649,    Adjusted R-squared:  0.6847 
F-statistic: 9.542 on 15 and 44 DF,  p-value: 2.193e-09</code></pre>
</div>
</div>
<p>This model has exactly the same prediction values, residual sum of squares, and <span class="math inline">\(R^2\)</span> as the Ordinary Least Squares model with the 15 predictors. However, there are some insignificant coefficients in this model. By following Ronald Christensen (2019), we can drop the predictors corresponding to insignificant coefficients and build the PCR based on the predictors with significant effects.</p>
</section>
<section id="reduced-pcr-model" class="level3">
<h3 class="anchored" data-anchor-id="reduced-pcr-model">Reduced PCR Model</h3>
<p>The principal components with significant effects in the full model are:</p>
<p><span class="math display">\[PC_1, PC_3, PC_6, PC_7, PC_9, PC_{12}\]</span> These subsets of the principal components account for 51% of the variation in the original predictors (<span class="math inline">\(X_i\)</span>s). We may say that the other 49% of the variation is not significantly related to the response variable.</p>
<p>So the reduced model is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>reduced_pcr <span class="ot">&lt;-</span> <span class="fu">lm</span>(mort.norm <span class="sc">~</span>PC1<span class="sc">+</span>PC3<span class="sc">+</span>PC6<span class="sc">+</span>PC7<span class="sc">+</span>PC9<span class="sc">+</span>PC12,<span class="at">data=</span>data_pcr)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reduced_pcr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mort.norm ~ PC1 + PC3 + PC6 + PC7 + PC9 + PC12, 
    data = data_pcr)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.204896 -0.044088  0.009946  0.039480  0.178350 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.070e-17  9.510e-03   0.000  1.00000    
PC1          2.506e-01  3.461e-02   7.239 1.86e-09 ***
PC3         -3.187e-01  5.139e-02  -6.202 8.61e-08 ***
PC6          3.389e-01  7.516e-02   4.510 3.63e-05 ***
PC7         -2.787e-01  9.410e-02  -2.962  0.00457 ** 
PC9          3.000e-01  1.210e-01   2.480  0.01633 *  
PC12         4.698e-01  2.067e-01   2.273  0.02712 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.07366 on 53 degrees of freedom
Multiple R-squared:  0.7124,    Adjusted R-squared:  0.6799 
F-statistic: 21.88 on 6 and 53 DF,  p-value: 9.291e-13</code></pre>
</div>
</div>
<p><span class="math display">\[\hat{MORT}= 0.251PC_1-0.319PC_3+0.339PC_6 -0.279PC_7+0.3PC_9+0.470PC_{12} \]</span> We know each PC is a linear combination of all the original predictors, as follow:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>v<span class="ot">&lt;-</span> x.pca1<span class="sc">$</span>rotation[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">9</span>,<span class="dv">12</span>)]</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>v</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              PC1         PC3         PC6           PC7         PC9        PC12
PREC   0.34547927 -0.02681399  0.18274943  0.0122300215  0.51151942 -0.17601926
JANT   0.06525347  0.10601047  0.07812527  0.3619311068 -0.23356631 -0.24101083
JULT   0.34448633  0.07810160 -0.11519796  0.0916220376 -0.28233138 -0.09978717
OVR65 -0.16298426 -0.15617683 -0.13982856 -0.2099950699  0.12808606 -0.05467298
POPN   0.29727366 -0.03197863  0.02608699  0.0357241457  0.28659385 -0.37866246
EDUC  -0.28650500  0.42939325  0.03026891 -0.1511594424  0.19969300 -0.54147683
HOUS  -0.36076129  0.05492805  0.16212540  0.4952140194  0.01830232  0.24312314
DENS  -0.07150671 -0.44022545  0.38843232  0.3135946383  0.20656213 -0.21038293
NONW   0.30201160 -0.06118170  0.27224559 -0.1584901497  0.31499478  0.52782208
WWDRK -0.19645501  0.33332901  0.19059877 -0.4693591060  0.11833883  0.12389839
POOR   0.35785982 -0.02372060 -0.07130608 -0.0955324496 -0.10332675 -0.11595861
HC    -0.28277142 -0.23942847 -0.22451250  0.0161190104  0.24925081  0.00712984
NOX   -0.26496868 -0.31021837 -0.18868002 -0.0696956753  0.21192889 -0.08334923
SOx   -0.06750489 -0.51943188  0.30101327 -0.4347391026 -0.42183348 -0.20487054
HUMID -0.11330703  0.19118053  0.67584786 -0.0009569469 -0.11737073 -0.04085240</code></pre>
</div>
</div>
</section>
<section id="model-assumption-for-pcr" class="level3">
<h3 class="anchored" data-anchor-id="model-assumption-for-pcr">Model Assumption for PCR</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(reduced_pcr<span class="sc">$</span>fitted.values,reduced_pcr<span class="sc">$</span>residuals, <span class="at">xlab =</span> <span class="st">"fitted values for reduced PCR model"</span>, <span class="at">ylab =</span> <span class="st">"residuals of the reduced PCR model"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-residual-ey" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-residual-ey-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pcr_files/figure-html/fig-residual-ey-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-residual-ey-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Residual versus fitted values of reduced PCR model
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(reduced_pcr<span class="sc">$</span>residuals,<span class="at">breaks=</span><span class="dv">13</span>,<span class="at">xlab =</span> <span class="st">"residuals of the reduced PCR model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-hist-pcr" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hist-pcr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pcr_files/figure-html/fig-hist-pcr-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hist-pcr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Histogram for the residuals of the reduced PCR model
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(reduced_pcr<span class="sc">$</span>residuals)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(reduced_pcr<span class="sc">$</span>residuals)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(reduced_pcr<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  reduced_pcr$residuals
W = 0.97511, p-value = 0.2574</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-qq-pcr" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qq-pcr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="pcr_files/figure-html/fig-qq-pcr-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qq-pcr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Normal Q-Q plot for the residuals of the reduced PCR model
</figcaption>
</figure>
</div>
</div>
</div>
<p>It seems the residuals of the reduced PCR model does not violate the assumptions.</p>
</section>
<section id="final-pcr-model-in-terms-of-the-original-predictors" class="level3">
<h3 class="anchored" data-anchor-id="final-pcr-model-in-terms-of-the-original-predictors">Final PCR Model in Terms of the Original Predictors</h3>
<p>The reduced model meets all the model assumptions and we consider it as the final PCR model.</p>
<p>we can also rewrite the model in terms of the original predictors:</p>
<p><span class="math display">\[\hat{\beta_x}=V\hat{\beta_z}\]</span> where V is the vector of selected eigenvectors corresponding to selected principal components(<span class="math inline">\([PC_1, PC_3, PC_6, PC_7, PC_9, PC_{12}]\)</span>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>beta_x <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(v)<span class="sc">%*%</span><span class="fu">as.matrix</span>(reduced_pcr<span class="sc">$</span>coefficients)[<span class="sc">-</span><span class="dv">1</span>,]</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>beta_x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              [,1]
PREC   0.224434622
JANT  -0.275134190
JULT  -0.134740481
OVR65  0.032824886
POPN  -0.008324578
EDUC  -0.350718174
HOUS  -0.071287812
DENS   0.129797793
NONW   0.574088671
WWDRK  0.133659217
POOR   0.014219125
HC     0.003001698
NOX    0.012390616
SOx    0.149054464
HUMID  0.085606526</code></pre>
</div>
</div>
<p><span class="math display">\[
\begin{align}
\hat{MORT}&amp;=0.224(PREC)-0.275(JANT)-0.134(JULT)+0.032(OVR65)-0.008(POPN)\\
&amp;-0.350(EDUC)-0.071(HOUS)+0.129(DENS)+0.574(NONW)+0.574(WWDRK)\\
&amp;+0.014(POOR)+0.003(HC)+0.012(NO_x)+0149(SO_2)+0.085(HUMID)
\end{align}
\]</span></p>
<p>For this model <span class="math inline">\(R^2=0.712\)</span> which is 14% larger (better) than the corresponding Ridge model (with k=0.2). In terms of residual sum of squared, the ridge model slightly works better than PCR. The residual sum of squared for PCR model is <span class="math inline">\(\phi^*=0.287\)</span> , which is slightly larger than the residual sum of squares for the Ridge model. The coefficients estimated for predictors are not much different from the corresponding ones in the Ridge model, except for OVR65, WWDRK, and HC, which have different signs in the two models. For OVR65 and HC, the difference in sign may not be a concern, as the estimated coefficients for these two predictors in both models are close to zero and do not significantly affect the models. However, for WWDRK, the PCR model considers that WWDRK has a positive moderate effect on mortality, while the Ridge model considers a negligible effect of -0.034.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>